### ISSUE TITLE
Service wont start (paused)

### ISSUE THREAD

**Issue by joelhauxwell** [EBOOZ/TeamsStatus#23]
Hello,

I followed the instructions to the letter to install this and although the service appears in the services list, its status is paused and it wont start.

I didn't get any errors whilst following the instructions until the last line where i get:

```
PS C:\Scripts> Start-Service -Name "Microsoft Teams Status Monitor"
Start-Service : Failed to start service 'Microsoft Teams Status Monitor (Microsoft Teams Status Monitor)'.
At line:1 char:1
+ Start-Service -Name "Microsoft Teams Status Monitor"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

PS C:\Scripts>
```

Any ideas?

Thanks,

**Comment by EBOOZ** [comment]
What happens when you try to start the script directly in a PowerShell prompt?

**Comment by joelhauxwell** [comment]
Thanks for your reply.  The message I copy/pasted above was directly from the PowerShell prompt.

**Comment by EBOOZ** [comment]
Yeah, but you try to start the service via PowerShell. What happens when you run Get-TeamsStatus.ps1 directly from the prompt?

**Comment by joelhauxwell** [comment]
Ah that's interesting, i get this:

![image](https://user-images.githubusercontent.com/71120697/111774223-164d1b00-88a7-11eb-944a-63a69d0dd69a.png)

Looks like it cant connect to my HA.

I have checked the Long-Lived Access Token and the URL of my HA box - this is the config

![image](https://user-images.githubusercontent.com/71120697/111774591-97a4ad80-88a7-11eb-8170-13e895d6deed.png)

I suspect the $HAUrl may be formatted incorrectly?

Thanks.

**Comment by joelhauxwell** [comment]
A bit of progress - i realised that the HA ip address possibly needed the port adding, so i have done that and now the error doesn't appear in PowerShell

![image](https://user-images.githubusercontent.com/71120697/111791088-c8daa900-88ba-11eb-9247-e524a16a0365.png)

However, in HA i just get 'unknown' for status and activity:

![image](https://user-images.githubusercontent.com/71120697/111791197-e445b400-88ba-11eb-91a5-e612ac2760de.png)

I have rebooted the HA pi and my PC.

Thanks,

**Comment by EBOOZ** [comment]
I think something got messed up when adding the sensors to your configuration. The sensor that get updated are not input_text, but template sensors:
```
sensor:
  - platform: template
    sensors:
      teams_status: 
        friendly_name: "Microsoft Teams status"
        value_template: "{{states('input_text.teams_status')}}"
        icon_template: "{{state_attr('input_text.teams_status','icon')}}"
        unique_id: sensor.teams_status
      teams_activity:
        friendly_name: "Microsoft Teams activity"
        value_template: "{{states('input_text.teams_activity')}}"
        unique_id: sensor.teams_activity
```
So the sensors that get updated are sensor.teams_status and sensor.teams_activity.
